spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia
    username: postgres
    password: Flamengotri22
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace